project:
  type: website

website:
  title: "E155 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Labs.qmd
        text: Labs
      - href: Resources.qmd
        text: Resources
      - href: blog.qmd
        text: Blogs


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



